apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir-pv-spark
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: "192.168.10.1"
    path: "/home/nfs/hivemr3/orange5"
