apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hivemr3
  name: workdir-pvc
  labels: {}
spec:
  resources:
    requests:
      storage: 10Gi
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
